# Numpy
## 什麼是Numpy?
![](https://i.imgur.com/X0pj3xu.png)

## 複習 List

In [5]:
lst1 =[1,2,3,4]
lst2 =[5,6,7,8]
print(lst1,lst2)

[1, 2, 3, 4] [5, 6, 7, 8]


## 建立Numpy 陣列

In [6]:
import numpy as np
np1 = np.array(lst1)
print(np1)

array([1, 2, 3, 4])

## 觀察陣資料型態

In [7]:
print(np1.dtype)

int64


## 轉換資料型態(整數改為浮點數)

In [8]:
tmp = np1.astype(np.float64)
tmp.dtype

dtype('float64')

## 陣列運算
lst1 = [1, 2, 3, 4]<br>lst2 = [5, 6, 7, 8]

In [10]:
np1*3

array([ 3,  6,  9, 12])

In [11]:
#陣列相加
np2 = np.array(lst2)
np1 + np2

array([ 6,  8, 10, 12])

In [12]:
#陣列相乘
np1 * np2

array([ 5, 12, 21, 32])

## 陣列中取值和定義新的數值
lst1 = [1, 2, 3, 4]<br>lst2 = [5, 6, 7, 8]

In [14]:
np1[2]

3

In [16]:
#取出索引值1~3的資料 
np1[1:3]

array([2, 3])

In [17]:
#從索引值1取到最後一個元素的寫法
np1[1:]

array([2, 3, 4])

In [21]:
#從右到左取資料
np1[-3]

2

In [24]:
#修改特定位置的資料:將索引值０的數字改為18
np1[0]=18
np1
np1[0]=1

## 將一維陣列改為二維陣列
矩陣

In [25]:
np1 = np1.reshape((2,2))
np1

array([[1, 2],
       [3, 4]])

In [26]:
np2 = np2.reshape((2,2))
np2

array([[5, 6],
       [7, 8]])

## 矩陣相乘
![](https://i.imgur.com/DLAVQD1.png)

In [27]:
#矩陣乘法
np1.dot(np2)

array([[19, 22],
       [43, 50]])